alias salths='sudo salt-call state.highstate'
alias salthslocal='sudo salt-call -c /tmp/cde_overlay/config --local state.highstate'
alias salthslocaldev='sudo salt-call -c /tmp/cde_overlay/config --file-root /tmp/cde_overlay/src/src2 --local state.highstate'
alias segmentb='export ONET_SEGMENT="B_INT";echo $ONET_SEGMENT'
alias segmentc='export ONET_SEGMENT="C_DEV";echo $ONET_SEGMENT'
alias segmenta='export ONET_SEGMENT="A_PROD";echo $ONET_SEGMENT'
alias segmentd='export ONET_SEGMENT="C_"${USER^^};echo $ONET_SEGMENT'
alias cds='cde ucs start ${USER}'
alias nb='npm run build'
alias setsamba='sudo smbpasswd -a "$USER"'
alias eksprep='aws eks --region eu-central-1 update-kubeconfig --name k8s-apps-v1'
alias addsshkey='ssh-add ~/.ssh/id_ed25519'
